language: go

go:
  - 1.4
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - mkdir -p $HOME/gopath/src/sourcegraph.com/sourcegraph
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/sourcegraph.com/sourcegraph/vcsstore
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/sourcegraph.com/sourcegraph/vcsstore

install:
  - git config --global user.email "a@a.com"
  - git config --global user.name "a"

  - export PATH=$PATH:$HOME/gopath/bin
  - export GOBIN=$HOME/gopath/bin
  - export TEST_CROSSREPO_DIFF_NUM_THREADS=500

# hg >~ 2.5 is needed, but Travis CI's Ubuntu 12.04 ships with hg ~2.0
  - sudo add-apt-repository -y ppa:mercurial-ppa/releases
  - sudo apt-get update
  - sudo apt-get install mercurial

  # install hglib for hg blame
  - sudo easy_install python-hglib

  - cd $TRAVIS_BUILD_DIR
  - go get -u github.com/tools/godep

  - godep go install ./cmd/vcsstore

script:
  - godep go test -race -v ./...
